# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freqli < Formula
  desc "Analyze shell history command frequency"
  homepage "https://github.com/Shobhit-Nagpal/freqli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/freqli/releases/download/v1.0.0/freqli_Darwin_x86_64.tar.gz"
      sha256 "84fcfe26e6925715e41f31ba63f3092648e953fb278ecec404c905767d31f91d"

      def install
        bin.install "main"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shobhit-Nagpal/freqli/releases/download/v1.0.0/freqli_Darwin_arm64.tar.gz"
      sha256 "cfe74878b71efdd110fcea80f94f02faaf107f065a50b378fe0660bcd84cb3a3"

      def install
        bin.install "main"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Shobhit-Nagpal/freqli/releases/download/v1.0.0/freqli_Linux_x86_64.tar.gz"
      sha256 "1a9fc0599c557b191ef2fb7227edb5d7a06754a1520ef35ff07f8d00414339fb"

      def install
        bin.install "main"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shobhit-Nagpal/freqli/releases/download/v1.0.0/freqli_Linux_arm64.tar.gz"
      sha256 "d92ce402a7d0c8716066400306f6814ca9cde9243770bc86c4ca99ac4a531e8b"

      def install
        bin.install "main"
      end
    end
  end
end
